import { push } from "./git";
import { currentlyMergedTaskIds, type Goal, goalCounts, readGoal, writeGoal } from "./goal";
import { resolveBackend } from "./prhost";
import { resolveReceipt, resolveReceiptRaw, sha256 } from "./receipt";

/**
 * Renders the PR body from the goal's `merges` log — only tasks currently
 * merged into the run branch, never the full `task_ids` list — so a failed or
 * still-in-flight task simply doesn't appear, and the outstanding count says
 * so explicitly rather than implying full completion.
 */
export function renderPrBody(cwd: string, goal: Goal): string {
  const merged = currentlyMergedTaskIds(goal);
  const counts = goalCounts(goal);
  const lines = [
    `Proof of work for goal \`${goal.id}\`: ${goal.goal}`,
    "",
    `${counts.merged} of ${counts.total} task(s) merged into \`${goal.run_branch}\`` +
      (counts.outstanding > 0 ? ` — ${counts.outstanding} outstanding.` : "."),
    "",
    "| Task | Oracle | Exit | Receipt sha256 |",
    "| --- | --- | --- | --- |",
  ];
  for (const taskId of merged) {
    const receipt = resolveReceipt(cwd, taskId);
    const raw = resolveReceiptRaw(cwd, taskId);
    if (!receipt || !raw) {
      throw new Error(
        `receipt for merged task ${taskId} is missing — the run branch is inconsistent`,
      );
    }
    const exitCode = receipt.runs?.at(-1)?.exit_code ?? receipt.exit_code ?? "?";
    lines.push(`| \`${taskId}\` | \`${receipt.oracle.run}\` | ${exitCode} | \`${sha256(raw)}\` |`);
  }
  lines.push("", "_Generated by `sddx pr create` from verified receipts — not hand-written._");
  return lines.join("\n");
}

export interface CreatePrOptions {
  title?: string;
}

export interface CreatePrResult {
  prUrl: string;
  branch: string;
  taskIds: string[];
}

/**
 * The full `sddx pr create --goal <id>` path: push the goal's run branch
 * as-is (whatever subset of tasks has merged so far — no completeness gate,
 * no reconstruction) and open a PR/MR from it. Partial-goal PRs are the
 * default, not an exception.
 */
export function createGoalPr(cwd: string, id: string, opts: CreatePrOptions = {}): CreatePrResult {
  const goal = readGoal(cwd, id);
  if (goal.shipped) {
    throw new Error(
      `goal ${id} already shipped as ${goal.shipped.pr_url} (${goal.shipped.at}) — ` +
        "re-running pr create would open a duplicate PR; nothing to do",
    );
  }

  const backend = resolveBackend(cwd);
  const auth = backend.authStatus(cwd);
  if (!auth.ok) {
    throw new Error(`${backend.name} is not authenticated: ${auth.message}`);
  }
  // Host-side check, not just the local `shipped` marker: that marker lives
  // in a plain, never-committed goal file (see `runbranch.ts`) that a stray
  // `git clean` could wipe — asking the host directly is what actually
  // prevents a duplicate PR in that case.
  const existing = backend.findPr(cwd, goal.run_branch);
  if (existing) {
    throw new Error(
      `goal ${id}'s run branch already has an open PR: ${existing.url} — ` +
        "re-running pr create would open a duplicate; nothing to do",
    );
  }

  push(cwd, goal.run_branch);
  const body = renderPrBody(cwd, goal);
  const title = opts.title ?? goal.goal;
  const prUrl = backend.openPr(cwd, { branch: goal.run_branch, title, body });

  // plain fs write, deliberately never committed — see `runbranch.ts`
  goal.shipped = { pr_url: prUrl, at: new Date().toISOString() };
  writeGoal(cwd, goal);

  return { prUrl, branch: goal.run_branch, taskIds: currentlyMergedTaskIds(goal) };
}
