import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { commit, currentBranch, git, push, stagePath } from "./git";
import { checkGoalComplete, type Goal, goalPath, readGoal, writeGoal } from "./goal";
import { buildGoalBranch } from "./prbranch";
import { resolveBackend } from "./prhost";
import { type Receipt, receiptPath, sha256 } from "./receipt";
import { markShipped, readTask, taskPath, writeTask } from "./task";
import { removeWorktreeForced, worktreesDir } from "./worktree";

/**
 * Renders the PR body from the receipts already sitting in the goal
 * worktree's tree — every task's receipt is part of its cherry-picked
 * commit, so by the time the branch is built there is nothing left to
 * hand-author. Throws if a receipt is unexpectedly missing (a corrupt
 * cherry-pick), rather than silently omitting a task's proof.
 */
export function renderPrBody(worktreePath: string, goal: Goal): string {
  const lines = [
    `Proof of work for goal \`${goal.id}\`: ${goal.goal}`,
    "",
    "| Task | Oracle | Exit | Receipt sha256 |",
    "| --- | --- | --- | --- |",
  ];
  for (const taskId of goal.task_ids) {
    const rPath = receiptPath(worktreePath, taskId);
    if (!existsSync(rPath)) {
      throw new Error(
        `receipt for task ${taskId} is missing from the goal branch — the cherry-pick is incomplete`,
      );
    }
    const raw = readFileSync(rPath);
    const receipt = JSON.parse(raw.toString("utf8")) as Receipt;
    const exitCode = receipt.runs?.at(-1)?.exit_code ?? receipt.exit_code ?? "?";
    lines.push(`| \`${taskId}\` | \`${receipt.oracle.run}\` | ${exitCode} | \`${sha256(raw)}\` |`);
  }
  lines.push("", "_Generated by `sddx pr create` from verified receipts — not hand-written._");
  return lines.join("\n");
}

/**
 * Records that a task shipped by committing the `shipped` marker onto the
 * task's own branch — never pushed (only the goal branch is), since this is
 * purely local bookkeeping `cleanup` reads back later.
 */
function shipTask(cwd: string, taskId: string, goalId: string, prUrl: string): void {
  const branch = `sddx/${taskId}`;
  const mark = (workPath: string): void => {
    const task = readTask(workPath, taskId);
    markShipped(task, goalId, prUrl);
    writeTask(workPath, task);
    // scoped to the task's own state file — `-A` would also sweep up any
    // other uncommitted content sitting in `workPath` into this commit when
    // `workPath` is the shared main checkout, not an isolated worktree
    git(workPath, "add", taskPath(workPath, taskId));
    git(workPath, "commit", "-qm", `sddx(${taskId}): mark shipped in goal ${goalId}`);
  };

  if (currentBranch(cwd) === branch) {
    mark(cwd);
    return;
  }
  const existingWtPath = join(worktreesDir(cwd), taskId);
  if (existsSync(existingWtPath)) {
    mark(existingWtPath);
    return;
  }
  const tmpPath = join(worktreesDir(cwd), `ship-${taskId}`);
  git(cwd, "worktree", "add", "-q", tmpPath, branch);
  try {
    mark(tmpPath);
  } finally {
    removeWorktreeForced(cwd, tmpPath);
  }
}

export interface CreatePrOptions {
  title?: string;
}

export interface CreatePrResult {
  prUrl: string;
  branch: string;
  taskIds: string[];
}

/**
 * The full `sddx pr create --goal <id>` path: completeness gate, auth
 * preflight, cherry-pick branch construction, push, receipt-derived body,
 * host PR open, then the `shipped` marker on every task and the goal itself.
 */
export function createGoalPr(cwd: string, id: string, opts: CreatePrOptions = {}): CreatePrResult {
  const completeness = checkGoalComplete(cwd, id);
  if (!completeness.complete) {
    const reasons = completeness.blocking.map((b) => `${b.task_id} (${b.reason})`).join(", ");
    throw new Error(`goal ${id} is not complete — blocking: ${reasons}`);
  }
  const goal = readGoal(cwd, id);
  if (goal.shipped) {
    throw new Error(
      `goal ${id} already shipped as ${goal.shipped.pr_url} (${goal.shipped.at}) — ` +
        "re-running pr create would open a duplicate PR; nothing to do",
    );
  }

  const backend = resolveBackend(cwd);
  const auth = backend.authStatus(cwd);
  if (!auth.ok) {
    throw new Error(`${backend.name} is not authenticated: ${auth.message}`);
  }

  const built = buildGoalBranch(cwd, id, goal.task_ids);
  let prUrl: string;
  try {
    // push lives inside this try too: a failed push (network, permission,
    // non-fast-forward) must not leak the worktree — a retry with a leftover
    // worktree/branch on disk would fail `buildGoalBranch`'s own `worktree add`
    push(cwd, built.branch);
    const body = renderPrBody(built.worktreePath, goal);
    const title = opts.title ?? goal.goal;
    prUrl = backend.openPr(cwd, { branch: built.branch, title, body });
  } finally {
    removeWorktreeForced(cwd, built.worktreePath);
  }

  for (const taskId of goal.task_ids) {
    shipTask(cwd, taskId, id, prUrl);
  }
  goal.shipped = { pr_url: prUrl, at: new Date().toISOString() };
  writeGoal(cwd, goal);
  // narrow commit, same reasoning as goal registration in cmdGoalCreate — the
  // goal's `shipped` marker is what cleanup's corroboration check ultimately
  // trusts, so it can't be left as an uncommitted file in the main checkout
  stagePath(cwd, goalPath(cwd, goal.id));
  commit(cwd, `sddx: goal ${goal.id} shipped as ${prUrl}`);

  return { prUrl, branch: built.branch, taskIds: goal.task_ids };
}
