// Deterministic BOARD.md renderer: pure filesystem reads over the workspace's
// .sddx plus each worktree's own task file. Same inputs, same bytes — rows are
// id-sorted and the output carries no timestamps, so idle regeneration never
// dirties the working tree.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Receipt } from "./lib/receipt";
import type { TaskState } from "./lib/task";
import { worktreesDir } from "./lib/worktree";

interface BoardRow {
  id: string;
  phase: string;
  sentence: string;
  workspace: string;
  iterations: string;
  receipt: string;
  allow: string;
}

const DASH = "—";

const cell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function receiptRef(dir: string, id: string): string {
  const path = join(dir, `${id}.json`);
  if (!existsSync(path)) return DASH;
  try {
    return `#${(JSON.parse(readFileSync(path, "utf8")) as Receipt).seq}`;
  } catch {
    return "unreadable";
  }
}

function taskRow(taskPath: string, id: string, receiptsDirs: string[]): BoardRow {
  let t: TaskState;
  try {
    t = JSON.parse(readFileSync(taskPath, "utf8")) as TaskState;
  } catch {
    return {
      id,
      phase: "UNREADABLE",
      sentence: "task file failed to parse",
      workspace: DASH,
      iterations: DASH,
      receipt: DASH,
      allow: DASH,
    };
  }
  let receipt = DASH;
  for (const dir of receiptsDirs) {
    receipt = receiptRef(dir, id);
    if (receipt !== DASH) break;
  }
  return {
    id: t.id,
    phase: t.phase,
    sentence: t.task,
    workspace: t.workspace.mode,
    iterations: String(t.iterations),
    receipt,
    allow: t.allow.length > 0 ? t.allow.join(", ") : DASH,
  };
}

const jsonIds = (dir: string): string[] =>
  existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith(".json"))
        .map((f) => f.slice(0, -".json".length))
        .sort()
    : [];

export function renderBoard(cwd: string): string {
  const rows = new Map<string, BoardRow>();
  const mainReceipts = join(cwd, ".sddx", "receipts");

  for (const id of jsonIds(join(cwd, ".sddx", "tasks"))) {
    rows.set(id, taskRow(join(cwd, ".sddx", "tasks", `${id}.json`), id, [mainReceipts]));
  }
  // worktree copies are the live ones — they win over a same-id workspace row
  const wtDir = worktreesDir(cwd);
  if (existsSync(wtDir)) {
    for (const id of readdirSync(wtDir).sort()) {
      const taskPath = join(wtDir, id, ".sddx", "tasks", `${id}.json`);
      if (!existsSync(taskPath)) continue;
      rows.set(id, taskRow(taskPath, id, [join(wtDir, id, ".sddx", "receipts"), mainReceipts]));
    }
  }

  const lines = ["<!-- generated by sddx — do not edit -->", "", "# sddx board", ""];
  if (rows.size === 0) {
    lines.push("_No tasks registered._", "");
    return lines.join("\n");
  }
  lines.push(
    "| Task | Phase | Sentence | Workspace | Iter | Receipt | Allow |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  );
  for (const id of [...rows.keys()].sort()) {
    const r = rows.get(id) as BoardRow;
    lines.push(
      `| ${cell(r.id)} | ${r.phase} | ${cell(r.sentence)} | ${r.workspace} | ${r.iterations} | ${r.receipt} | ${cell(r.allow)} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

export const boardPath = (cwd: string): string => join(cwd, ".sddx", "BOARD.md");

/** Write only when the rendered bytes differ; returns whether a write happened. */
export function writeBoard(cwd: string): { path: string; changed: boolean } {
  const path = boardPath(cwd);
  const rendered = renderBoard(cwd);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === rendered) return { path, changed: false };
  mkdirSync(join(cwd, ".sddx"), { recursive: true });
  writeFileSync(path, rendered);
  return { path, changed: true };
}
