// Deterministic BOARD.md renderer: pure filesystem reads over the workspace's
// .sddx plus each worktree's own task file. Same inputs, same bytes — rows are
// id-sorted and the output carries no timestamps, so idle regeneration never
// dirties the working tree.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stuckThreshold } from "./lib/config";
import type { Receipt } from "./lib/receipt";
import { blockedOn, type TaskState } from "./lib/task";
import { worktreesDir } from "./lib/worktree";

interface BoardRow {
  id: string;
  phase: string;
  rawPhase: string;
  dependsOn?: string;
  sentence: string;
  workspace: string;
  iterations: string;
  receipt: string;
  allow: string;
}

const DASH = "—";

const cell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function receiptRef(dir: string, id: string): string {
  const path = join(dir, `${id}.json`);
  if (!existsSync(path)) return DASH;
  try {
    return `#${(JSON.parse(readFileSync(path, "utf8")) as Receipt).seq}`;
  } catch {
    return "unreadable";
  }
}

function taskRow(
  taskPath: string,
  id: string,
  receiptsDirs: string[],
  threshold: number,
): BoardRow {
  let t: TaskState;
  try {
    t = JSON.parse(readFileSync(taskPath, "utf8")) as TaskState;
  } catch {
    return {
      id,
      phase: "UNREADABLE",
      rawPhase: "UNREADABLE",
      sentence: "task file failed to parse",
      workspace: DASH,
      iterations: DASH,
      receipt: DASH,
      allow: DASH,
    };
  }
  let receipt = DASH;
  for (const dir of receiptsDirs) {
    receipt = receiptRef(dir, id);
    if (receipt !== DASH) break;
  }
  return {
    id: t.id,
    phase: t.stuck && t.stuck.count >= threshold ? `${t.phase} ⚠stuck` : t.phase,
    rawPhase: t.phase,
    ...(t.depends_on ? { dependsOn: t.depends_on } : {}),
    sentence: t.task,
    workspace: t.workspace.mode,
    iterations: String(t.iterations),
    receipt,
    allow: t.allow.length > 0 ? t.allow.join(", ") : DASH,
  };
}

/** "Flagged worktrees" section from .sddx/sweep.json; empty when nothing is flagged. */
function flagLines(cwd: string): string[] {
  const path = join(cwd, ".sddx", "sweep.json");
  if (!existsSync(path)) return [];
  let entries: Array<{ path: string; reason: string }>;
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8")) as { skipped?: unknown };
    entries = Array.isArray(parsed.skipped)
      ? (parsed.skipped as Array<{ path: string; reason: string }>)
      : [];
  } catch {
    return [
      "## Flagged worktrees",
      "",
      "- sweep state unreadable — `.sddx/sweep.json` failed to parse",
      "",
    ];
  }
  if (entries.length === 0) return [];
  const sorted = [...entries].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return [
    "## Flagged worktrees",
    "",
    ...sorted.map((e) => `- \`${cell(String(e.path))}\` — ${cell(String(e.reason))}`),
    "",
  ];
}

const jsonIds = (dir: string): string[] =>
  existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith(".json"))
        .map((f) => f.slice(0, -".json".length))
        .sort()
    : [];

export function renderBoard(cwd: string): string {
  const rows = new Map<string, BoardRow>();
  const mainReceipts = join(cwd, ".sddx", "receipts");
  const threshold = stuckThreshold(cwd);

  for (const id of jsonIds(join(cwd, ".sddx", "tasks"))) {
    rows.set(id, taskRow(join(cwd, ".sddx", "tasks", `${id}.json`), id, [mainReceipts], threshold));
  }
  // worktree copies are the live ones — they win over a same-id workspace row
  const wtDir = worktreesDir(cwd);
  if (existsSync(wtDir)) {
    for (const id of readdirSync(wtDir).sort()) {
      const taskPath = join(wtDir, id, ".sddx", "tasks", `${id}.json`);
      if (!existsSync(taskPath)) continue;
      // worktrees carry their own .sddx/config.json — judge stuck by the same
      // threshold the gates inside that worktree use
      rows.set(
        id,
        taskRow(
          taskPath,
          id,
          [join(wtDir, id, ".sddx", "receipts"), mainReceipts],
          stuckThreshold(join(wtDir, id)),
        ),
      );
    }
  }

  const lines = ["<!-- generated by sddx — do not edit -->", "", "# sddx board", ""];
  if (rows.size === 0) {
    lines.push("_No tasks registered._", "");
  } else {
    lines.push(
      "| Task | Phase | Depends | Sentence | Workspace | Iter | Receipt | Allow |",
      "| --- | --- | --- | --- | --- | --- | --- | --- |",
    );
    for (const id of [...rows.keys()].sort()) {
      const r = rows.get(id) as BoardRow;
      // Share the CLI's blocked derivation so the board and `blockedOn` agree even
      // when an ancestor's worktree was swept (resolveTaskState reads its branch tip).
      const blocker =
        r.rawPhase === "DONE" ? null : blockedOn(cwd, { id, depends_on: r.dependsOn });
      const phase = blocker ? `${r.phase} ⏸blocked-on-${blocker}` : r.phase;
      lines.push(
        `| ${cell(r.id)} | ${phase} | ${r.dependsOn ? cell(r.dependsOn) : DASH} | ${cell(r.sentence)} | ${r.workspace} | ${r.iterations} | ${r.receipt} | ${cell(r.allow)} |`,
      );
    }
    lines.push("");
  }
  lines.push(...flagLines(cwd));
  return lines.join("\n");
}

export const boardPath = (cwd: string): string => join(cwd, ".sddx", "BOARD.md");

/** Write only when the rendered bytes differ; returns whether a write happened. */
export function writeBoard(cwd: string): { path: string; changed: boolean } {
  const path = boardPath(cwd);
  const rendered = renderBoard(cwd);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === rendered) return { path, changed: false };
  mkdirSync(join(cwd, ".sddx"), { recursive: true });
  writeFileSync(path, rendered);
  return { path, changed: true };
}
